services:

  # PostgreSQL Database
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eu1189
      POSTGRES_DB: jwt-auth-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "jwt-auth-db", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # pgAdmin for Database Management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=emree.unaldi@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=eu1189
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5051:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - microservices-network
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5050/misc/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Token Storage and Caching
  redis-db:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Insight for Redis Management
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5541:5540"
    volumes:
      - redis_insight_data:/data
    environment:
      - REDIS_URL=redis://redis-db:6379
    networks:
      - microservices-network
    depends_on:
      redis-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5540/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  redis_insight_data:

networks:
  microservices-network:
    driver: bridge